### ISSUE TITLE
bug: invalid window id when using float layout, `:TermNew layout=float ...`

### ISSUE THREAD

**Issue by MadKuntilanak** [waiting-for-dev/ergoterm.nvim#16]
Hi, I just found this plugin today and started trying a few things.
I was trying it out using the default config from the README, and when I ran the command:

`:TermNew layout=float ...`

I got the following error:

```
  Error  06:39:04 PM E5108: Lua: .../share/nvim/lazy/ergoterm.nvim/lua/ergoterm/terminal.lua:453: Invalid window id: 1463
stack traceback:
	[C]: in function 'nvim_set_current_win'
	.../share/nvim/lazy/ergoterm.nvim/lua/ergoterm/terminal.lua:453: in function 'focus'
	.../share/nvim/lazy/ergoterm.nvim/lua/ergoterm/terminal.lua:533: in function 'toggle'
	..config/nvim/lua/r/plugins/terminal.lua:59: in function <...config/nvim/lua/r/plugins/terminal.lua:56>
```

After doing a bit of digging, I noticed this line in the latest commit:

[https://github.com/waiting-for-dev/ergoterm.nvim/blob/97736049fc182a7053d6d057f4d1fefb750d1140/lua/ergoterm/autocommands.lua#L34](https://github.com/waiting-for-dev/ergoterm.nvim/blob/97736049fc182a7053d6d057f4d1fefb750d1140/lua/ergoterm/autocommands.lua#L34)

From what I saw, this didn’t happen in the previous commit, like this:

```lua
local ergoterm_pattern = { "term://*#ergoterm#*", "term://*::ergoterm::*" }
```

When I compared it to the previous commit, it looks like the older version didn’t have this issue. 
Not sure if this is related, but thought I’d share just in case it helps!

Let me know if I can provide more info..

**Comment by waiting-for-dev** [comment]
Thanks for reporting. I'll take a look.

**Comment by waiting-for-dev** [comment]
Fixed! Thanks again for opening this one.

**Comment by MadKuntilanak** [comment]
> Fixed! Thanks again for opening this one.

Thanks a lot for the quick fix!

But it seems like there's still an issue when:

1. I'm currently inside a floating terminal
2. I try to create another floating terminal

Then I get this error:

```
   Error  09:37:12 PM E5108: Lua: .../share/nvim/lazy/ergoterm.nvim/lua/ergoterm/terminal.lua:407: Invalid window id: 1207
stack traceback:
	[C]: in function 'nvim_set_current_win'
	.../share/nvim/lazy/ergoterm.nvim/lua/ergoterm/terminal.lua:407: in function 'open'
	.../share/nvim/lazy/ergoterm.nvim/lua/ergoterm/terminal.lua:450: in function 'focus'
	.../share/nvim/lazy/ergoterm.nvim/lua/ergoterm/terminal.lua:539: in function 'toggle'
	...config/nvim/lua/r/plugins/terminal.lua:65: in function <...config/nvim/lua/r/plugins/terminal.lua:62>
```

**Comment by MadKuntilanak** [comment]
Also, when I run `:TermSelect` while I'm in a float terminal:

1. I’m inside a floating terminal
2. Open 4/5 floating terminal
2. Run `:TermSelect`, select terminal
3. Then this happens:

```
   Error  09:38:11 PM vim.schedule callback: ....local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:429: .../share/nvim/lazy/ergoterm.nvim/lua/ergoterm/terminal.lua:407: Invalid window id: 1272
stack traceback:
	[C]: in function 'nvim_set_current_win'
	.../share/nvim/lazy/ergoterm.nvim/lua/ergoterm/terminal.lua:407: in function 'open'
	.../share/nvim/lazy/ergoterm.nvim/lua/ergoterm/terminal.lua:450: in function 'focus'
	...al/share/nvim/lazy/ergoterm.nvim/lua/ergoterm/config.lua:119: in function 'fn'
	...im/lazy/ergoterm.nvim/lua/ergoterm/pickers/p_fzf_lua.lua:133: in function 'fn'
	...al/share/nvim/lazy/fzf-lua/lua/fzf-lua/profiles/hide.lua:69: in function 'fn'
	....local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:462: in function 'contents'
	....local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:424: in function <....local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:419>
	[C]: in function 'xpcall'
	....local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:419: in function 'fn'
	....local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:143: in function <....local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:142>
stack traceback:
	[C]: in function 'error'
	....local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:429: in function 'fn'
	....local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:143: in function <....local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:142>
```

*note:
Sorry for not opening a separate issue,. this could be tied to the same floating terminal problem.
Just wanted to surface it in case it's a case that wasn’t fully covered during testing or in some specific workflows.
